kind : Cluster
apiVersion: kind.x-k8s.io/v1alpha4


nodes: 
- role: control-plane
  image: kindest/node:v1.31.2
- role: worker
  image: kindest/node:v1.31.2
- role: worker
  image: kindest/node:v1.31.2
  extraPortMappings:
  # Map port 30000 on the host to port 30000 on the control-plane node (for Flask backend)
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
  # Map port 30001 on the host to port 30001 on the control-plane node (for frontend)
      - containerPort: 30001
        hostPort: 30001
        protocol: TCP